const Ease = Object.freeze({
	InBack: Symbol("easeInBack"),
	OutBack: Symbol("easeOutBack"),
	InOutBack: Symbol("easeInOutBack"),
	InBounce: Symbol("easeInBounce"),
	OutBounce: Symbol("easeOutBounce"),
	InOutBounce: Symbol("easeInOutBounce"),
	InCirc: Symbol("easeInCirc"),
	OutCirc: Symbol("easeOutCirc"),
	InOutCirc: Symbol("easeInOutCirc"),
	InCubic: Symbol("easeInCubic"),
	OutCubic: Symbol("easeOutCubic"),
	InOutCubic: Symbol("easeInOutCubic"),
	InElastic: Symbol("easeInElastic"),
	OutElastic: Symbol("easeOutElastic"),
	InOutElastic: Symbol("easeInOutElastic"),
	InExpo: Symbol("easeInExpo"),
	OutExpo: Symbol("easeOutExpo"),
	InOutExpo: Symbol("easeInOutExpo"),
	InQuad: Symbol("easeInQuad"),
	OutQuad: Symbol("easeOutQuad"),
	InOutQuad: Symbol("easeInOutQuad"),
	InQuart: Symbol("easeInQuart"),
	OutQuart: Symbol("easeOutQuart"),
	InOutQuart: Symbol("easeInOutQuart"),
	InQuint: Symbol("easeInQuint"),
	OutQuint: Symbol("easeOutQuint"),
	InOutQuint: Symbol("easeInOutQuint"),
	InSine: Symbol("easeInSine"),
	OutSine: Symbol("easeOutSine"),
	InOutSine: Symbol("easeInOutSine")
});
export default Ease;